// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJR1Shb6GQSivB9MRW6Mm441kwZDvyc1c',
    appId: '1:857411037860:web:147bb8ee9318fd7042d431',
    messagingSenderId: '857411037860',
    projectId: 'eraasoft-5fd7a',
    authDomain: 'eraasoft-5fd7a.firebaseapp.com',
    storageBucket: 'eraasoft-5fd7a.appspot.com',
    measurementId: 'G-BES64YE30P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAqphVlPBIWumm2zWN-ksIH_bzopjBamg',
    appId: '1:857411037860:android:4e5932c2d259ee4742d431',
    messagingSenderId: '857411037860',
    projectId: 'eraasoft-5fd7a',
    storageBucket: 'eraasoft-5fd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzd7aqgIqQ9Nh9xqCMfFR7G6RsQGePWZc',
    appId: '1:857411037860:ios:00d1b7cec6c5351a42d431',
    messagingSenderId: '857411037860',
    projectId: 'eraasoft-5fd7a',
    storageBucket: 'eraasoft-5fd7a.appspot.com',
    iosBundleId: 'com.eraasoft.flutter113',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzd7aqgIqQ9Nh9xqCMfFR7G6RsQGePWZc',
    appId: '1:857411037860:ios:36febafbd9a2ad6a42d431',
    messagingSenderId: '857411037860',
    projectId: 'eraasoft-5fd7a',
    storageBucket: 'eraasoft-5fd7a.appspot.com',
    iosBundleId: 'com.eraasoft.flutter113.RunnerTests',
  );
}
